apiVersion: v1
kind: Service
metadata:
  name: schema-registry
  labels:
    app: schema-registry
spec:
  type: {{ .Values.service.type }}
  selector:
    app: schema-registry
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
