{{- if .Values.schemaRegistry.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.schemaRegistry.secret.name }}
type: Opaque
stringData:
  username: {{ .Values.schemaRegistry.secret.username | quote }}
  password: {{ .Values.schemaRegistry.secret.password | quote }}
  userInfo: "{{ .Values.schemaRegistry.secret.username }}:{{ .Values.schemaRegistry.secret.password }}"
{{- end }}
