apiVersion: v1
kind: Service
metadata:
  name: ksqldb-server
  labels:
    app: ksqldb-server
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ksqldb-server
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8088
