apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: internal
      port: {{ .Values.service.headless.portInternal }}
      targetPort: {{ .Values.service.headless.portInternal }}
    - name: client
      port: {{ .Values.service.headless.portClient }}
      targetPort: {{ .Values.service.headless.portClient }}
    - name: controller
      port: {{ .Values.service.headless.portController }}
      targetPort: {{ .Values.service.headless.portController }}
