apiVersion: v1
kind: Service
metadata:
  name: schema-registry
spec:
  selector:
    app: schema-registry
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.schemaRegistry.port }}
  type: ClusterIP
